### ISSUE TITLE
Clicking Check for update in the settings menu returns a 404

### ISSUE THREAD

**Issue by philiptruax** [adueck/journee-diary#2]
The github page linked in the settings menu returns a 404 page not found. 
![image](https://user-images.githubusercontent.com/11514343/41734141-1a42f64e-7554-11e8-96f9-dda9e585929f.png)
![image](https://user-images.githubusercontent.com/11514343/41734163-2b5c103c-7554-11e8-9c74-fd0786fde6c9.png)

**Comment by philiptruax** [comment]
This is probably just a permissions issue if it's working for you.

**Comment by adueck** [comment]
Sorry for the very slow response on this. Thank you for noticing this. This happened because I changed my site address. Now I've fixed it.
