### ISSUE TITLE
few ideas

### ISSUE THREAD

**Issue by richo67** [adueck/journee-diary#3]
HI,

great tool, I was looking for something like that, running it on windows and Linux too.
What would you think about following few ideas (I am sure you though about them too)

1. option to choose font (for all and whole entries - global)
2. spell check with choice of language

**Comment by subacoustic** [comment]
Great tool, with a dark mode it would be perfect, love the simplicity of it... thanks!  Dark mode please!

**Comment by subacoustic** [comment]
The ability to add images would also be appreciated (apologies, I am no coder)

**Comment by adueck** [comment]
Sorry, I am busy with other projects, and I'm not adding new features to this old project right now. 😢  I'm glad you like it though, and yes those are all great features! I may get around to adding them later when I have time for this.

I'm happy to accept pull requests though if someone wants to add to it.
